name: Helm Chart Workflow

on: 
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - shared/charts/microservice/**

permissions:
  id-token: write
  contents: read

env:
  solutionName: "[nf:solution-name]"
  chartVersion: "1.0.${{github.run_number}}"
  netfusionVer: "8.0.42"
  registryName: "[nf:arc-name]"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Helm
      uses: Azure/setup-helm@v3  
      
    - name: Package Helm Chart
      run: |
        helm package ./shared/charts/microservice \
        --version $chartVersion \
        --app-version ${netfusionVer}

    - name: Archive Packaged Helm Chart  
      uses: actions/upload-artifact@v4
      with:
        name: packaged-helm-chart
        path: |
          microservice-${{ env.chartVersion }}.tgz 

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: "Az CLI login"
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Download Packaged Helm Chart
      uses: actions/download-artifact@v4
      with:
        name: packaged-helm-chart

    - name: Install Helm
      uses: Azure/setup-helm@v3  

    - name: Registry Login
      run: az acr login --name ${registryName}

    - name: Push Helm Chart to Repo
      run: helm push microservice-${chartVersion}.tgz oci://${registryName}.azurecr.io/${solutionName}/charts
  
      
