name: Solution.Context Workflow

on: workflow_dispatch
  # push:
  #   branches: [ master ]

permissions:
  id-token: write
  contents: read

env:
  environment: dev

  microserviceRoot: ./microservices
  microserviceDir: Solution.Context
  microserviceName: [nf:microservice-name]
  microserviceVer: "1.0"

  aksResourceGroup: [nf:aks-group]
  aksName: [nf:aks-name]
  aksNamespace: [nf:aks-namespace]

  imageRegistry: [nf:registry]

  helmChart: netfusion-microservice
  helmChartVer: "1.0.5"

  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: List Sources
      run: ls -R .

    - name: Set Image Tag Variable
      run: |
          echo "TAGGED_IMAGE=${imageRegistry}/${microserviceName}:${microserviceVer}.${{github.run_number}}" >> $GITHUB_ENV

    - name: Build Microservice Image
      run: |
        docker build ${microserviceRoot}/${microserviceDir} \
        --file ${microserviceRoot}/${microserviceDir}/Dockerfile \
        --tag ${{ env.TAGGED_IMAGE }}

    - name: List Images
      run: docker images

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Log Into ACR
      run: az acr login --name ${imageRegistry}

    - name: Push Image to Repository
      run: docker image push ${{ env.TAGGED_IMAGE }}

    - name: Archive Microservice Helm Settings  
      uses: actions/upload-artifact@v4
      with:
        name: microservice-helm-settings
        path: ${{ env.microserviceRoot }}/${{ env.microserviceDir}}/deployment/*-values.yaml

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: development
    env:
      helmChartVer: "1.0.5"
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Download Microservice Helm Settings
      uses: actions/download-artifact@v4
      with:
        name: microservice-helm-settings

    - name: List Downloaded Artifacts
      run: ls -R .

    - name: Log Into ACR
      run: az acr login --name ${imageRegistry}

    - name: Log Into AKS
      run: az aks get-credentials --resource-group ${aksResourceGroup} --name ${aksName}

    - name: Deploy Microservice Chart
      run: | 
        helm upgrade ${microserviceName} \
          --install oci://${imageRegistry}/helm/${helmChart} \
          --version ${helmChartVer} \
          -n ${aksNamespace} \
          --values ${environment}-values.yaml
