solution: [nf:solution-name]
name: [nf:service-name]

serviceAccount: [nf:service-account]
port: [nf:port]

extraLabels: {}
podAnnotations: {}
podLabels: {}

image:
  registry: [nf:registry]
  pullPolicy: IfNotPresent

probes:
  startupPath: /mgt/startup-check
  readinessPath: /mgt/ready-check
  livenessPath: /mgt/health-check