name: Branches Build

on:
  push:
    branches:
    - develop
    - current-feature 
    
    paths:
    - 'netfusion/**'
env:
  solution: ./netfusion/NetFusion.sln
  packageDir: ./netfusion/pkgs

jobs:
  build:
    env:
      buildVersion: '3.3.${{github.run_number}}'
      nugetAuthToken: ${{ secrets.NuGetAPIKey }}
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.101
    - name: Print Variables
      run: echo $buildVersion
    - name: Restore Dependencies
      run: dotnet restore $solution
    - name: Build for Test
      run: dotnet build --no-restore --version-suffix $buildVersion $solution
    - name: Test
      run: dotnet test --no-build --verbosity normal $solution
