name: Microservice Template

on:
  push:
    branches: [ master ]
    paths:
      - 'tools/**'
env:
  solutionRoot: ./tools/dotnet/Templates/MicroService/content/src
  nugetSpec: ./tools/dotnet/Templates/MicroService/MicroService.nuspec  

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      buildVersion: '7.0.${{github.run_number}}'
      nugetAuthToken: ${{ secrets.NuGetAPIKey }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.200
    - name: Setup NuGet.exe 
      uses: NuGet/setup-nuget@v1.0.5
      with:
        nuget-version: latest
    - name: Restore Dependencies
      run: dotnet restore $solutionRoot/Solution.Context.sln
    - name: Build Template
      run: dotnet build --no-restore -c Release --version-suffix $buildVersion $solutionRoot/Solution.Context.sln
    - name: Package Template
      run: nuget pack $nugetSpec -Version $buildVersion 
    - name: Push Template to Repository
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k $nugetAuthToken --skip-duplicate ./**/NetFusion.*.nupkg


