name: Microservice Template

on:
  push:
    branches: [ master ]
    paths:
      - 'utilities/**'
env:
  solutionRoot: ./utilities/templates

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      buildVersion: '8.0.${{github.run_number}}'
      nugetAuthToken: ${{ secrets.NuGetAPIKey }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.101

    - name: Restore Microservice Template Dependencies
      run: dotnet restore $solutionRoot/microservice/src/Solution.Context.sln

    - name: Build Microservice Template
      run: dotnet build --no-restore -c Release --version-suffix $buildVersion $solutionRoot/microservice/src/Solution.Context.sln

    - name: Package Templates
      run: dotnet pack ./utilities/templatepack.csproj --version-suffix $buildVersion

    - name: Push Template to Repository
      run: dotnet nuget push -s https://api.nuget.org/v3/index.json -k $nugetAuthToken --skip-duplicate ./**/NetFusion.*.nupkg


