name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - 'tools/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.405
    - name: Print
      run: echo $github.run_number
